#!/usr/bin/env python3
"""
auto_bet.py — Automated VFL bet placement agent.
Reads picks from vfl_llm_predictor or vfl_rapid_scanner and places bets
via the MSport API / browser.

REFACTORED: Uses msport_api.py for all data fetching (odds, event IDs, markets).
No HTML scraping. Direct JSON API calls for fixture data.
Browser fallback only for actual bet submission (if no API endpoint exists).
"""
import json
import logging
import os
import sys
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

from msport_api import (
    get_current_match_day_info,
    get_event_list,
    extract_1x2_odds,
    extract_over_under_odds,
    extract_all_markets,
)

logger = logging.getLogger(__name__)

# ─── Configuration ──────────────────────────────────────────────────────────
STATE_DIR = os.path.expanduser("~/.hermes")
os.makedirs(STATE_DIR, exist_ok=True)

Llm_PICKS_FILE = os.path.join(STATE_DIR, "vfl_llm_picks.json")
RAPID_STATE_FILE = os.path.join(STATE_DIR, "vfl_rapid_state.json")
BET_LEDGER_FILE = os.path.join(STATE_DIR, "vfl_bet_ledger.json")

# Stake calculation config
DEFAULT_STAKE = 1.00  # Base stake in units
MAX_STAKE = 5.00
CONFIDENCE_STAKE_MULT = 0.02  # Additional stake per confidence point above 80%

# Bet placement — set to True if a native API endpoint is available
USE_API_BETTING = False  # Set to True once bet placement endpoint is discovered


# ─── Ledger ─────────────────────────────────────────────────────────────────


def load_ledger() -> Dict[str, Any]:
    if os.path.exists(BET_LEDGER_FILE):
        try:
            with open(BET_LEDGER_FILE) as f:
                return json.load(f)
        except (json.JSONDecodeError, OSError):
            pass
    return {"bets": [], "bankroll": {"initial": 100.0, "current": 100.0}}


def save_ledger(ledger: Dict[str, Any]) -> None:
    with open(BET_LEDGER_FILE, "w") as f:
        json.dump(ledger, f, indent=2)


# ─── Pick loading ───────────────────────────────────────────────────────────


def load_llm_picks() -> List[Dict[str, Any]]:
    """Load picks generated by vfl_llm_predictor."""
    if not os.path.exists(Llm_PICKS_FILE):
        return []
    try:
        with open(Llm_PICKS_FILE) as f:
            all_picks = json.load(f)
        # Filter to picks not yet placed
        return [p for p in all_picks if not p.get("placed")]
    except (json.JSONDecodeError, OSError):
        return []


def load_rapid_picks_from_cache() -> List[Dict[str, Any]]:
    """
    Load picks that were output by vfl_rapid_scanner.
    The rapid scanner only prints to stdout; we reconstruct from its cache.
    """
    # Rapid scanner saves a seen set, not pick data directly.
    # For auto_bet, we rely on LLM picks primarily.
    return []


# ─── Pick verification ──────────────────────────────────────────────────────


def verify_pick_with_live_odds(pick: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """
    Verify a pick's odds are still available (not expired/changed).
    Fetches fresh data from the API and confirms the selection still exists.
    Returns updated pick dict with current odds, or None if unavailable.
    """
    event_id = pick.get("event_id")
    if not event_id:
        return None

    match_days = get_event_list()
    if not match_days:
        return None

    # Find event by ID
    for md in match_days:
        for event in md.get("events", []):
            if event.get("eventId") == event_id:
                # Found the event — check market
                market = pick.get("market", "")
                selection = pick.get("selection", "")

                if "Under 3.5" in selection:
                    ou = extract_over_under_odds(event)
                    total_35 = ou.get("total=3.5", {})
                    current_odds = total_35.get("Under 3.5", 0.0)
                    if current_odds > 0:
                        updated = dict(pick)
                        updated["current_odds"] = current_odds
                        updated["odds"] = f"{current_odds:.2f}"
                        return updated
                elif selection == "Home":
                    odds_1x2 = extract_1x2_odds(event)
                    if odds_1x2.get("Home", 0) > 0:
                        updated = dict(pick)
                        updated["current_odds"] = odds_1x2["Home"]
                        updated["odds"] = f'{odds_1x2["Home"]:.2f}'
                        return updated
                elif selection == "Away":
                    odds_1x2 = extract_1x2_odds(event)
                    if odds_1x2.get("Away", 0) > 0:
                        updated = dict(pick)
                        updated["current_odds"] = odds_1x2["Away"]
                        updated["odds"] = f'{odds_1x2["Away"]:.2f}'
                        return updated

                # Event found but market/selection not available
                return None

    return None


# ─── Stake calculation ──────────────────────────────────────────────────────


def calculate_stake(pick: Dict[str, Any]) -> float:
    """
    Calculate stake based on confidence and odds.
    Kelly Criterion-inspired: f* = (bp - q) / b
    where b = decimal odds - 1, p = win probability, q = 1-p
    """
    confidence_str = pick.get("confidence", "90%")
    try:
        confidence = float(confidence_str.rstrip("%")) / 100.0
    except (ValueError, AttributeError):
        confidence = 0.85

    odds = float(pick.get("odds", 0))
    if odds <= 1.0:
        return DEFAULT_STAKE

    b = odds - 1
    q = 1 - confidence

    # Kelly fraction
    kelly = (b * confidence - q) / b if b > 0 else 0

    # Conservative: use 25% Kelly
    stake = kelly * 0.25 * 100  # Scale to units

    # Clamp
    stake = max(DEFAULT_STAKE, min(MAX_STAKE, stake))
    return round(stake, 2)


# ─── Bet placement ──────────────────────────────────────────────────────────


def place_bet_via_api(pick: Dict[str, Any], stake: float) -> bool:
    """
    Place a bet via the MSport API.
    NOTE: This function will be implemented once the bet placement endpoint
    is discovered. Currently logs the intended bet.
    """
    logger.info(
        "API BET: %s vs %s | %s @%s | stake=%.2f | conf=%s",
        pick.get("home", "?"),
        pick.get("away", "?"),
        pick.get("selection", "?"),
        pick.get("odds", "?"),
        stake,
        pick.get("confidence", "?"),
    )

    # Placeholder for future API integration
    # endpoint = "https://www.msport.com/api/ng/betting/place/bet"
    # payload = { ... event_id, market_id, selection_id, stake ... }
    # response = fetch_json(endpoint, method="POST", data=payload)

    print(f"  ⏳ API bet placement not yet implemented — would bet {stake:.2f}u")
    return False


def place_bet_via_browser(pick: Dict[str, Any], stake: float) -> bool:
    """
    Fallback: log bet details for manual or browser-based placement.
    """
    print(f"  🖥️ Browser fallback: {pick['home']} vs {pick['away']}")
    print(f"     Pick: {pick['selection']} @{pick['odds']} (stake: {stake:.2f}u)")
    print(f"     Conf: {pick['confidence']}")
    return False


# ─── Main ───────────────────────────────────────────────────────────────────


def main() -> None:
    ledger = load_ledger()
    bankroll = ledger.get("bankroll", {}).get("current", 100.0)

    print(f"💰 **VFL Auto-Bet Agent**")
    print(f"   Bankroll: {bankroll:.2f}u")
    print()

    # 1. Fetch current state
    info = get_current_match_day_info()
    if info:
        print(f"   Season: {info.get('seasonName')} | MD{info.get('matchDay')} ({info.get('status')})")
    print()

    # 2. Load unpicked bets from LLM predictor
    llm_picks = load_llm_picks()
    print(f"📥 Pending LLM picks: {len(llm_picks)}")

    if not llm_picks:
        print("✅ No pending picks to place")
        # Still check rapid scanner picks
        return

    # 3. Verify each pick against live odds
    verified_picks = []
    for pick in llm_picks:
        print(f"🔍 Verifying: {pick.get('home')} vs {pick.get('away')} — {pick.get('selection')} @{pick.get('odds')}")

        verified = verify_pick_with_live_odds(pick)
        if verified:
            if float(verified.get("odds", 0)) <= 0:
                print(f"   ❌ Selection no longer available")
                continue
            print(f"   ✅ Verified — odds still valid @{verified.get('odds')}")
            verified_picks.append(verified)
        else:
            print(f"   ❌ Event not found or expired")
            # Mark as expired
            pick["expired"] = True

    if not verified_picks:
        print("\n😴 No verified picks to bet on")
        return

    # 4. Calculate stakes and place bets
    print(f"\n📊 **Placing {len(verified_picks)} bet(s)**")
    print()

    placed_count = 0
    total_stake = 0.0

    for pick in verified_picks:
        stake = calculate_stake(pick)

        # Check bankroll
        if stake > bankroll:
            print(f"   ⛔ Insufficient bankroll for {pick['home']} vs {pick['away']}")
            continue

        print(f"🎯 {pick['home']} vs {pick['away']}")
        print(f"   Selection: {pick['selection']} @{pick['odds']}")
        print(f"   Stake: {stake:.2f}u | Confidence: {pick['confidence']}")

        # Place bet
        if USE_API_BETTING:
            success = place_bet_via_api(pick, stake)
        else:
            success = place_bet_via_browser(pick, stake)

        if success:
            placed_count += 1
            total_stake += stake
            bankroll -= stake

            # Mark pick as placed
            pick["placed"] = True
            pick["placed_at"] = datetime.now(timezone.utc).isoformat()
            pick["stake"] = stake

            # Log to ledger
            ledger["bets"].append({
                "pick": pick,
                "stake": stake,
                "placed_at": pick["placed_at"],
                "settled": False,
            })
            ledger["bankroll"]["current"] = round(bankroll, 2)
            save_ledger(ledger)

            print(f"   ✅ Bet placed!")
        else:
            print(f"   ⏳ Bet queued for manual placement")

        print()

    # Summary
    print(f"📈 **Summary:** {placed_count} bet(s) placed | Total stake: {total_stake:.2f}u")
    print(f"💰 **Bankroll remaining:** {bankroll:.2f}u")

    # Save updated picks (mark them as placed/verified)
    try:
        if os.path.exists(Llm_PICKS_FILE):
            with open(Llm_PICKS_FILE) as f:
                existing = json.load(f)
        else:
            existing = []

        # Update old picks with new state
        verified_ids = {vp.get("id") for vp in verified_picks}
        updated = []
        for old in existing:
            if old.get("id") in verified_ids:
                # Find the matching verified pick
                match = next((vp for vp in verified_picks if vp.get("id") == old.get("id")), old)
                updated.append(match)
            else:
                updated.append(old)
        # Add any new verified picks not in original
        for vp in verified_picks:
            if vp.get("id") not in {o.get("id") for o in existing}:
                updated.append(vp)

        with open(Llm_PICKS_FILE, "w") as f:
            json.dump(updated, f, indent=2)
    except Exception as e:
        logger.warning("Failed to save picks: %s", e)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"[ERROR] auto_bet failed: {e}", file=sys.stderr)
        sys.exit(1)
