#!/usr/bin/env python3
"""
vfl_trap_interceptor.py

This script intercepts the latest JSON data generated by the live predictor,
scans for our purely algorithmic traps (The Absolute Crusher and Guaranteed Loser),
and posts an isolated MASTER LOCK alert to a Discord Forum channel.
"""

import json
import logging
from pathlib import Path
import sys
import requests
from datetime import datetime, timezone

BASE_DIR = Path("/home/ubuntu/faith-workspace/vfl-complete-data")
SCRIPTS_DIR = Path("/home/ubuntu/faith-workspace/vfl-empire/scripts")
JSON_PATH = SCRIPTS_DIR / "predictions_latest.json"
WEBHOOK_URL = "https://discord.com/api/webhooks/1310617631627055114/aH2l-0B-YV6b3q15b_8Bw99mJ6261mNnKj5uT21L0IeLz351kQ2V75k_O8H9oT2fB-z"

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("trap_interceptor")

def get_streak(form_str):
    if not form_str or form_str == '?': return '?'
    last_char = form_str[-1]
    count = 0
    for char in reversed(form_str):
        if char == last_char: count += 1
        else: break
    return f"{last_char}{count}"

def send_to_discord(title, content):
    import subprocess
    logger.info("Sending trap alert to Discord via hermes CLI...")
    try:
        # Route to specific thread in the forum
        res = subprocess.run(
            ["/home/ubuntu/.local/bin/hermes", "send", "--to", "discord:1507922324072960031:1516261573033721907", f"**{title}**\n\n{content}"],
            capture_output=True,
            text=True,
            check=True
        )
        logger.info(f"Successfully posted to Discord. Output: {res.stdout.strip()}")
    except subprocess.CalledProcessError as e:
        logger.error(f"Error posting to Discord via hermes (exit {e.returncode}): {e.stderr.strip()}")
    except Exception as e:
        logger.error(f"Error posting to Discord via hermes: {e}")

def run_interception():
    if not JSON_PATH.exists():
        logger.error(f"Cannot find {JSON_PATH}")
        return

    with open(JSON_PATH, "r") as f:
        data = json.load(f)

    if not data.get('matchdays'):
        logger.info("No matchdays in JSON.")
        return

    md = data['matchdays'][0]
    season = md.get('season_id', 'Unknown')
    matchday = md.get('matchday', 'Unknown')
    
    header = f"🦅 ALGORITHMIC TRAPS | {season} - MD {matchday}"
    
    traps_found = []

    for fix in md.get('fixtures', []):
        home = fix.get('home', 'Unknown')
        away = fix.get('away', 'Unknown')
        odds = fix.get('odds', {})
        
        markets = fix.get('markets', [])
        h_rank, a_rank, h_form, a_form = '?', '?', '?', '?'
        if markets:
            gates = markets[0].get('gate_result', {}).get('gates', {})
            ls = gates.get('league_standing', {})
            h_rank = ls.get('h_rank', '?')
            a_rank = ls.get('a_rank', '?')
            h_form = ls.get('h_form', '?')
            a_form = ls.get('a_form', '?')
            
        h_streak = get_streak(h_form)
        a_streak = get_streak(a_form)
        
        h_bracket = 'Top4' if h_rank != '?' and int(h_rank) <= 4 else ('Bot4' if h_rank != '?' and int(h_rank) >= 13 else 'Mid')
        a_bracket = 'Top4' if a_rank != '?' and int(a_rank) <= 4 else ('Bot4' if a_rank != '?' and int(a_rank) >= 13 else 'Mid')
        
        is_trap = False
        trap_desc = ""
        bet_action = ""
        
        # Crusher: Only when favorite plays at home
        if h_bracket == 'Top4' and h_streak.startswith('W') and int(h_streak[1:]) >= 3:
            if a_bracket == 'Bot4' and a_streak.startswith('L') and int(a_streak[1:]) >= 3:
                is_trap = True; trap_desc = "🔥 THE ABSOLUTE CRUSHER (HOME)"
                bet_action = f"**Home Win (1) + U3.5** [Odds: {odds.get('home_win')} / {odds.get('u35')}]"
                
        # Guaranteed Loser
        if h_bracket == 'Bot4' and h_streak.startswith('L') and int(h_streak[1:]) >= 4:
            is_trap = True; trap_desc = "💀 GUARANTEED LOSER (Gravity Well)"
            bet_action = f"**Away Win or Draw (X2)** against {home} [Odds: {odds.get('away_win')} / {odds.get('draw')}]"
            
        if a_bracket == 'Bot4' and a_streak.startswith('L') and int(a_streak[1:]) >= 4:
            is_trap = True; trap_desc = "💀 GUARANTEED LOSER (Gravity Well)"
            bet_action = f"**Home Win or Draw (1X)** against {away} [Odds: {odds.get('home_win')} / {odds.get('draw')}]"

        if is_trap:
            traps_found.append({
                "fixture": f"{home} [R{h_rank}, {h_streak}] vs {away} [R{a_rank}, {a_streak}]",
                "desc": trap_desc,
                "action": bet_action
            })
            
    content = ""
    if traps_found:
        content += "## 🚨 MASTER LOCKS IDENTIFIED 🚨\n\n"
        for t in traps_found:
            content += f"**Match:** {t['fixture']}\n"
            content += f"**Trap:** {t['desc']}\n"
            content += f"**Bet:** {t['action']}\n\n"
        content += "=> Action: Place these bets immediately.\n"
    else:
        content += "No extreme algorithmic traps active this matchday.\n"
        content += "=> Action: Wait for next matchday.\n"
        
    print(content)
    
    # Check if we already posted for this matchday to avoid spam
    state_file = SCRIPTS_DIR / ".trap_state"
    last_posted = ""
    if state_file.exists():
        with open(state_file, "r") as f:
            last_posted = f.read().strip()
            
    current_state = f"{season}-{matchday}"
    if last_posted != current_state:
        send_to_discord(f"MD {matchday} - {season}", content)
        with open(state_file, "w") as f:
            f.write(current_state)
    else:
        logger.info(f"Already posted to Discord for {current_state}")

if __name__ == "__main__":
    run_interception()
